config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'incidents#index'
  resources :incidents, only: [:index, :new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/incident.rb
class Incident < ApplicationRecord
  self.inheritance_column = :_type_disabled
end

app/models/type.rb
class Type < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  def index
    @incidents = Incident.all
  end

  def new
    @incident = Incident.new
  end

  def create
    @incident = Incident.create(incident_params)
    redirect_to root_path
  end

  private
  def incident_params
    params.permit(:type, :incidents_count)
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/views/incidents/index.html.haml
.navbar
  .ul.nav-justfuild.text-dark
    .li.nav-item
      %a.nab-link
        incident counter
      %a.nab-link
        -# home
      %a.nab-link
.Main
  .div.jumbotron.bg-secondary.text-light
    %h3 シンプルなカウンター
    %p
      1件の重大事故があれば、その背後に29件の軽度の事故があり、300件のインシデントが潜んでいる。
    %p
      これは経験則、ハインリッヒの法則として知られています。起こっているインシデント,
      改善可能な項目を把握して重大事故のリスクを減らしましょう。

  .container.no-gutters
    .row
      .col.bg-dark.col-3.text-light
        - @incidents.each do |post|
          =post.created_at

      .col
        -# %p 確認作業を行なっていたらチェック
        -# = check_box :incident, :confirmed, {class:'check_box'}, true, false
        = button_to "マニュアル(Software)", incidents_path(type:1), class: "btn btn-outline-dark"
        = button_to "道具・機器(Hardware)", incidents_path(type:2), class: "btn btn-outline-dark"
        = button_to "環境(Environment)", incidents_path(type:3), class: "btn btn-outline-dark"
        = button_to "個人的要素(Liveware)", incidents_path(type:4), class: "btn btn-outline-dark"
        -# %button.btn.btn-outline-dark
        -#   btn
        = Incident.group(:type).count(:type)
        = Incident.all.count
        -# = form_with model: @incident do |f|
        -#   = f.check_box :confirmed, {class:'check_box'}, true, false
        -#   %button.btn.btn-outline-dark
        -#     インシデント項目
        

        -# = form_with url: incidents_path do |f|
        -#   = check_box :incident, :confirmed, {class:'check_box'}, true, false
        -#   = button_to "インシデント項目4", incidents_path(type:4), class: "btn btn-outline-dark"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title IncidentCounter
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application'
  %body
    = yield